--------------------------------------------------------
--  File created - Friday-February-05-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "NSHAH23"."STUDENT" 
   (	"STDID" VARCHAR2(20 BYTE), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"STREET" VARCHAR2(40 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(20 BYTE), 
	"ZIP" VARCHAR2(20 BYTE), 
	"TELEPHONE" VARCHAR2(12 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"URL" VARCHAR2(20 BYTE), 
	"INTINUNI" VARCHAR2(20 BYTE), 
	"HIGHSCHLGRADMONTH" VARCHAR2(20 BYTE), 
	"HIGHSCHLGRADYEAR" VARCHAR2(20 BYTE), 
	"RECOS" VARCHAR2(20 BYTE), 
	"COMMENTS" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS"   NO INMEMORY ;
REM INSERTING into NSHAH23.STUDENT
SET DEFINE OFF;
Insert into NSHAH23.STUDENT (STDID,USERNAME,STREET,CITY,STATE,ZIP,TELEPHONE,EMAIL,URL,INTINUNI,HIGHSCHLGRADMONTH,HIGHSCHLGRADYEAR,RECOS,COMMENTS) values ('G01234567','Nupurs','Test','Test','Test','67483','243-987-9871','nupur23@gmail.com','http://www.gmail.com','Internet','May','2011','Likely','Enter comments here.');
Insert into NSHAH23.STUDENT (STDID,USERNAME,STREET,CITY,STATE,ZIP,TELEPHONE,EMAIL,URL,INTINUNI,HIGHSCHLGRADMONTH,HIGHSCHLGRADYEAR,RECOS,COMMENTS) values ('G01241234','Nupur','4400 University Drive','Fairfax','Virginia','22030','203-302-3300','nupur@gmu.edu','http://www.gmu.edu','Internet','May','1992','Very Likely','No Comments');
Insert into NSHAH23.STUDENT (STDID,USERNAME,STREET,CITY,STATE,ZIP,TELEPHONE,EMAIL,URL,INTINUNI,HIGHSCHLGRADMONTH,HIGHSCHLGRADYEAR,RECOS,COMMENTS) values ('G01234532','Test','12222 Emrald Ln','Chantilly','Virginia','22703','234-432-3433','test@gmail.com','http://www.gmail.com','Friends','September','2002','Very Likely','No Additional Comments.');
--------------------------------------------------------
--  DDL for Index SYS_C003001498
--------------------------------------------------------

  CREATE UNIQUE INDEX "NSHAH23"."SYS_C003001498" ON "NSHAH23"."STUDENT" ("STDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS" ;
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "NSHAH23"."STUDENT" MODIFY ("STDID" NOT NULL ENABLE);
  ALTER TABLE "NSHAH23"."STUDENT" ADD PRIMARY KEY ("STDID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS"  ENABLE;
